services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # основной порт RabbitMQ
      - "15672:15672" # веб-интерфейс RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  clickhouse-server:
    image: clickhouse/clickhouse-server
    environment:
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=password
    ports:
      - "8123:8123" # Adjust port as needed
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-init:/docker-entrypoint-initdb.d  # <-- тут init.sql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  worker:
    build: .
    container_name: celery_worker
    command: celery -A tasks worker --loglevel=info
    volumes:
      - .:/app
      - ./receipts:/app/receipts
    depends_on:
      - rabbitmq
      - clickhouse-server
    env_file:
      - .env   
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_BACKEND: rpc://
      CLICKHOUSE_HOST: clickhouse-server

volumes:
  clickhouse_data: {}